version: 0.2

phases:
  install:
  pre_build:
    commands:
      - echo "Preparing environment for deployment..."
  build:
    commands:
      - echo "Running build steps..."
  post_build:
    commands:
      - echo "Post build steps..."
      - echo "Starting CodeDeploy agent..."
