version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      php: 8.0
  pre_build:
    commands:
      - echo Installing dependencies...
      - apt update && apt-get update
      - apt install lsb-release ca-certificates apt-transport-https software-properties-common -y
      - add-apt-repository ppa:ondrej/php
      - apt install curl -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - rm awscliv2.zip
      - ./aws/install --update
      -  apt-get install  -y php8.0-imagick php8.0-curl  php8.0-mbstring php8.0-xml php8.0-mysql php8.0-imap php8.0-gd php8.0-zip php8.0-soap php8.0-redis  php8.0-tidy php8.0-xmlrpc
  build:
    commands:
      - echo Start building...
artifacts:
  files:
    - "**/*"
