version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  # Only specify Node.js runtime here
    commands:
      - echo "Installing dependencies..."
      # Update and install required packages
      - apt-get update -y
      - apt-get install -y \
        lsb-release ca-certificates apt-transport-https software-properties-common curl unzip \
        php8.0 php8.0-cli php8.0-fpm php8.0-mbstring php8.0-xml php8.0-mysql php8.0-imap php8.0-gd php8.0-zip \
        php8.0-soap php8.0-redis php8.0-tidy php8.0-xmlrpc php8.0-imagick
      # Add PHP repository for additional versions
      - add-apt-repository ppa:ondrej/php
      - apt-get update -y
      # Install AWS CLI
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - rm awscliv2.zip
      - ./aws/install --update
      # Install Composer (if it's not already in the environment)
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      # Optional: Install any additional dependencies or setup here
  build:
    commands:
      - echo "Start building..."
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - "**/*"
