version: 0.2

phases:
  install:
    runtime-versions:
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Running pre-build tasks..."
  build:
    commands:
      - echo "Start building..."

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - "**/*"
